stages:
- publish

before_script:
- npm install

publish:
  stage: publish
  image: node:8
  only:
  - tags
  script:
  - npm --no-git-tag-version version ${CI_COMMIT_TAG}
  - npm publish --access public
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
